Repository cczapatat/proyectoFinal1Grupo11_2025, pull requests merged in 2025-05, with the labels that each got.

#215 [HU-33] Crear servicio para Crear una nueva visita
  .github/workflows/push_feature_fix_branch.yml
  build-images.sh
  deployment/k8s-base-layer-deployment.yaml
  deployment/k8s-ingress-deployment.yaml
  deployment/secrets.yaml
  route/.dockerignore
  route/Dockerfile
  route/README.md
  route/__init__.py
  route/api/__init__.py
  route/api/routes.py
  route/http_services/__init__.py
  route/http_services/visit_http.py
  route/requirements.txt
  route/tests/__init__.py
  route/tests/conftest.py
  route/tests/functional/__init__.py
  route/tests/functional/test_health.py
  route/tests/functional/test_routes.py
  visit/.dockerignore
  visit/Dockerfile
  visit/README.md
  visit/__init__.py
  visit/api/__init__.py
  visit/api/visits.py
  visit/config/__init__.py
  visit/config/db.py
  visit/dtos/__init__.py
  visit/dtos/visit_in_dto.py
  visit/dtos/visit_product_in_dto.py
  visit/http_services/__init__.py
  visit/http_services/users_http.py
  visit/infrastructure/__init__.py
  visit/infrastructure/transaction.py
  visit/infrastructure/visit_product_repository.py
  visit/infrastructure/visit_repository.py
  visit/managers/__init__.py
  visit/managers/visit_manager.py
  visit/models/__init__.py
  visit/models/visit_model.py
  visit/models/visits_product_model.py
  visit/requirements.txt
  visit/schemas/__init__.py
  visit/schemas/create_visit_schema.py
  visit/tests/__init__.py
  visit/tests/conftest.py
  visit/tests/functional/__init__.py
  visit/tests/functional/test_health.py
  visit/tests/functional/test_visits.py
  web-smartstock/cypress/e2e/spec.cy.ts
Labels: Feature, Tasks

#217 Fix/hu 036
  web-smartstock/src/app/store/store-assign-product/store-assign-product.component.spec.ts
  web-smartstock/src/app/store/store-assign-product/store-assign-product.component.ts
Labels: Bug

#224 Feature/hu 05
  web-smartstock/cypress/e2e/massive/massive-manufacturers-create/massive-manufacturers-create.spec.cy.ts
  web-smartstock/cypress/fixtures/manufacturers.csv
  web-smartstock/cypress/support/commands.ts
Labels: Feature, Tasks

#229 [HU-13] Listar Fabricantes con sus Productos
  .github/workflows/push_feature_fix_branch.yml
  product/api/products.py
  product/infrastructure/product_repository.py
  product/models/product_model.py
  product/tests/api/test_products.py
  web-smartstock/src/app/dtos/manufacturer.ts
  web-smartstock/src/app/manufacture/manufacture-list-products/manufacture-list-products.component.css
  web-smartstock/src/app/manufacture/manufacture-list-products/manufacture-list-products.component.html
  web-smartstock/src/app/manufacture/manufacture-list-products/manufacture-list-products.component.spec.ts
  web-smartstock/src/app/manufacture/manufacture-list-products/manufacture-list-products.component.ts
  web-smartstock/src/app/manufacture/manufacture.module.ts
  web-smartstock/src/app/product/product.ts
  web-smartstock/src/app/salespeople/salespeople.module.ts
  web-smartstock/src/app/services/manufacturer.service.spec.ts
  web-smartstock/src/app/services/manufacturer.service.ts
  web-smartstock/src/app/services/product.service.spec.ts
  web-smartstock/src/app/services/product.service.ts
  web-smartstock/src/assets/i18n/en-UK.json
  web-smartstock/src/assets/i18n/es-AR.json
  web-smartstock/src/assets/i18n/es-CO.json
Labels: Feature, Tasks

#230 [HU-13] Manufacturer List Products Cypress
  web-smartstock/cypress/e2e/manufacture/manufacture-list-products/manufacture-list-products.cy.ts
  web-smartstock/cypress/e2e/massive/massive-manufacturers-create/massive-manufacturers-create.spec.cy.ts
  web-smartstock/cypress/e2e/massive/massive-products-create/massive-products-create.spec.cy.ts
  web-smartstock/cypress/e2e/massive/massive-products-edit/massive-products-edit.spec.cy.ts
  web-smartstock/cypress/e2e/order/create-order/create-order.spec.cy.ts
  web-smartstock/cypress/e2e/salespeople/assing-customer/assign-customer.cy.ts
  web-smartstock/cypress/e2e/salespeople/list-clients/seller-list-clients.cy.ts
  web-smartstock/cypress/e2e/store/store-register/store-assign-product/store-assign-product.spec.cy.ts
  web-smartstock/cypress/support/commands.ts
  web-smartstock/src/app/manufacture/manufacture-list-products/manufacture-list-products.component.ts
Labels: Feature, Tasks

#231 [HU-032]
  route/api/routes.py
  route/http_services/visit_http.py
  route/tests/functional/test_routes.py
  visit/api/visits.py
  visit/dtos/client_in_dto.py
  visit/dtos/extended_visit_in_dto.py
  visit/infrastructure/visit_repository.py
  visit/managers/visit_manager.py
  visit/tests/functional/test_visits.py
Labels: Feature

#236 [HU-032] Paginated Visits
  visit/api/visits.py
  visit/infrastructure/visit_repository.py
  visit/managers/visit_manager.py
  visit/tests/functional/test_visits.py
Labels: Feature

#237 Feature/hu 032 3 mobile
  build-images.sh
  mobile-smartstock/app/src/androidTest/java/com/smartstock/myapplication/Utils.kt
  mobile-smartstock/app/src/androidTest/java/com/smartstock/myapplication/clientVisit/ListClientVisitTest.kt
  mobile-smartstock/app/src/main/java/com/smartstock/myapplication/MainActivity.kt
  mobile-smartstock/app/src/main/java/com/smartstock/myapplication/adapters/ClientVisitAdapter.kt
  mobile-smartstock/app/src/main/java/com/smartstock/myapplication/models/ClientSimple.kt
  mobile-smartstock/app/src/main/java/com/smartstock/myapplication/models/ClientVisit.kt
  mobile-smartstock/app/src/main/java/com/smartstock/myapplication/network/ClientVisitPagingSource.kt
  mobile-smartstock/app/src/main/java/com/smartstock/myapplication/network/NetworkServiceAdapter.kt
  mobile-smartstock/app/src/main/java/com/smartstock/myapplication/ui/clientVisit/ClientVisitFragment.kt
  mobile-smartstock/app/src/main/java/com/smartstock/myapplication/ui/clientVisit/ClientVisitViewModel.kt
  mobile-smartstock/app/src/main/java/com/smartstock/myapplication/ui/clientVisit/ClientVisitViewModelFactory.kt
  mobile-smartstock/app/src/main/res/layout/fragment_list_visits.xml
  mobile-smartstock/app/src/main/res/layout/visit_item.xml
  mobile-smartstock/app/src/main/res/menu/popup_menu.xml
  mobile-smartstock/app/src/main/res/navigation/nav_graph.xml
  mobile-smartstock/app/src/main/res/values-en-rUS/strings.xml
  mobile-smartstock/app/src/main/res/values-es-rCO/strings.xml
  mobile-smartstock/app/src/main/res/values-es-rES/strings.xml
  mobile-smartstock/app/src/main/res/values/strings.xml
  route/api/routes.py
  route/http_services/visit_http.py
Labels: Feature

#247 [HU-35] Monitor Backed - Publish Alarms
  .github/workflows/deployment_to_production.yml
  build-images.sh
  deployment/k8s-base-layer-deployment.yaml
  deployment/secrets.yaml
  monitor/Dockerfile
  monitor/consumer/stock_update.py
  monitor/infrastructure/alarm_repository.py
  monitor/infrastructure/firebase_database.py
  monitor/models/alarm_trigger.py
  monitor/requirements.txt
  monitor/tests/conftest.py
  monitor/tests/functional/test_alarms.py
  monitor/tests/src_mocks/firebase-cred.json
Labels: Feature, Tasks

#248 [HU-35] add logic for create alarm component
  web-smartstock/src/app/alarm/alarm-create/alarm-create.component.css
  web-smartstock/src/app/alarm/alarm-create/alarm-create.component.html
  web-smartstock/src/app/alarm/alarm-create/alarm-create.component.spec.ts
  web-smartstock/src/app/alarm/alarm-create/alarm-create.component.ts
  web-smartstock/src/app/alarm/alarm.module.ts
  web-smartstock/src/app/alarm/alarm.ts
  web-smartstock/src/app/product/product.module.ts
  web-smartstock/src/app/services/alarm.service.spec.ts
  web-smartstock/src/app/services/alarm.service.ts
  web-smartstock/src/assets/i18n/en-UK.json
  web-smartstock/src/assets/i18n/es-AR.json
  web-smartstock/src/assets/i18n/es-CO.json
  web-smartstock/src/environments/environment.development.ts
  web-smartstock/src/environments/environment.ts
Labels: Feature, Tasks

#252 Feature/hu 039
  mobile-smartstock/app/build.gradle.kts
  mobile-smartstock/app/src/main/java/com/smartstock/myapplication/MainActivity.kt
  mobile-smartstock/app/src/main/java/com/smartstock/myapplication/adapters/NotificationListAdapter.kt
  mobile-smartstock/app/src/main/java/com/smartstock/myapplication/models/NewsAlert.kt
  mobile-smartstock/app/src/main/java/com/smartstock/myapplication/network/FirebaseNotificationService.kt
  mobile-smartstock/app/src/main/java/com/smartstock/myapplication/ui/notifications/NotificationsListFragment.kt
  mobile-smartstock/app/src/main/java/com/smartstock/myapplication/ui/notifications/NotificationsListViewModel.kt
  mobile-smartstock/app/src/main/java/com/smartstock/myapplication/util/NotificationTracker.kt
  mobile-smartstock/app/src/main/res/drawable/ic_notifications_bell.xml
  mobile-smartstock/app/src/main/res/layout/fragment_notifications_list.xml
  mobile-smartstock/app/src/main/res/layout/list_item_notification.xml
  mobile-smartstock/app/src/main/res/menu/popup_menu.xml
  mobile-smartstock/app/src/main/res/navigation/nav_graph.xml
  mobile-smartstock/app/src/main/res/values-en-rUS/strings.xml
  mobile-smartstock/app/src/main/res/values-es-rCO/strings.xml
  mobile-smartstock/app/src/main/res/values-es-rES/strings.xml
  mobile-smartstock/app/src/main/res/values/strings.xml
  mobile-smartstock/build.gradle.kts
Labels: Feature

#255 [HU-241] Accesibilidad
  web-smartstock/cypress/e2e/order/create-order/create-order.spec.cy.ts
  web-smartstock/src/app/manufacture/manufacture-list-products/manufacture-list-products.component.html
  web-smartstock/src/app/order/order-create/order-create.component.css
  web-smartstock/src/app/order/order-create/order-create.component.html
  web-smartstock/src/assets/i18n/en-UK.json
  web-smartstock/src/assets/i18n/es-AR.json
  web-smartstock/src/assets/i18n/es-CO.json
Labels: Feature, Bug

#256 [HU-240]
  web-smartstock/src/app/salespeople/salespeople-register/salespeople-register.component.html
  web-smartstock/src/app/store/store-assign-product/store-assign-product.component.html
Labels: Bug
